sudo: required
dist: trusty
language: rust
branches:
  only:
  - master
matrix:
  fast_finish: false
  include:
  - rust: stable
cache:
  apt: true
  directories:
  - $TRAVIS_BUILD_DIR/target
  - $HOME/.cargo
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - gcc-4.8
    - g++-4.8
    - oracle-java8-set-default
script:
  - echo 'Running tests' && echo -en 'travis_fold:start:tests'
  - cargo test --all
  - echo -en 'travis_fold:end:tests'
  - echo 'Building in release mode' && echo -en 'travis_fold:start:build.release'
  - cargo build --release
  - echo -en 'travis_fold:end:build.release'
  - echo 'Running regtests from ./tools/regtests.sh' && echo -en 'travis_fold:start:regtests'
  - ./tools/regtests.sh
  - echo -en 'travis_fold:end:regtests'
  - echo 'Running bench from ./tools/bench.sh' && echo -en 'travis_fold:start:bench'
  - ./tools/bench.sh
  - echo -en 'travis_fold:end:bench'
after_success: |
  [ true ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  ./tools/doc.sh &&
  echo '<meta http-equiv=refresh content=0;url=pbtc/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - CXX="g++-4.8"
  - CC="gcc-4.8"
  - secure: RPpiXGV2RgRNv/S5XICdym33pauO5PNQu06+0kIuap6acsT6rjWZDeKU0kXIkCyv7XGu6TAE3m1/N6DSFvoeObdoodzakpUnzI9ysC9UbGbX3KgFAILrsuD+Th0HR1yZ2+boXEnetl7lp87X6m3HL4dz7ccuRJOGQFCdzo4iQd4RXMJXq1nS8pXYOnOiGtWy/K6SBqHus42End303vR6ptd71iuEYmX2qL5LUpXRQ5JuvE78JL4v5e1jrLwwrIG5hr3ej+EICiEKjAtZcv3C/CYq2+V7T8mI8FQFBsVG56FxP1Qq0G1jnv6r8i/pLb342DiQapeQZ+CZ1vHv3Ruzxm4+T9VLkwIcI5kOZmbOjt/BnO1yHFMr6uslxYuyEvSLZXsvnB7Qi2cB/nFWxi8nk19CzuYy2hjrnDA/bfeii65oQ4hyqAuF6QvHgZtMmSONbea679b1mbl9K67EWt04J4k67Hfuj6HvmIOT3KF0TPXO6K4b6a4OJ43PinNSWtIOlCb4658HrfUBTUEe1XN14uC/F8dyFw8PTrw/VQKkmNEDRvI0AuWF1s+qN1u1mm+CpyJaqxcPloUR+RgVBk3KrRd/Gm6neunx07G6STv/S2mGCZ2ZRIUpbSqha7XTmHltoWZRYFeM3dhVMXe3hgEYuJfm4n7HxGvp4b1s1ckenPI=
  - RUST_BACKTRACE=1
