[package]
name = "p2p"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
tokio-core = "0.1"
parking_lot = "0.3"
futures = "0.1"
futures-cpupool = "0.1"
time = "0.1"
rand = "0.3"

primitives = { path = "../primitives" }
bitcrypto = { path = "../crypto" }
serialization = { path = "../serialization" }
message = { path = "../message" }
